import tornado.web

from utils.auth import require_jwt_auth


@require_jwt_auth
class ProductsHandler(tornado.web.RequestHandler):
    def set_default_headers(self):
        self.set_header("Access-Control-Allow-Origin", "*")
        self.set_header("Access-Control-Allow-Headers", "*")
        self.set_header("Access-Control-Allow-Methods", "POST, OPTIONS")

    def options(self, *args):
        self.set_status(204)
        self.finish()

    def get(self):
        """
        ---
        tags:
        - Products
        summary: Get products
        "description": |
            Get product list.
        produces:
        - application/json
        responses:
            200:
                "description": Successfully authenticated
                schema:
                    type: array
                    items:
                        $ref: '#/definitions/ProductSchema'
        """

        response = {
            "data": [
                {
                    "code": "F2201144",
                    "description": "CAVIWIPES SALVIETTE DISINF. SPESSE BUSTE 20X45PZ",
                    "brand": "KERR",
                    "image": "00088219_.JPG",
                    "discount_percent": 45,
                    "original_price": 134.0,
                    "discount_price": 73.7,
                },
                {
                    "code": "F2201169",
                    "description": "ZETA 3 POP UP SALVIETTE DISINF. 100PZ",
                    "brand": "ZHERMACK",
                    "image": "00096940_.JPG",
                    "discount_percent": 45,
                    "original_price": 13.5,
                    "discount_price": 7.4,
                },
                {
                    "code": "F2201129",
                    "description": "OPTIBOND GEL ETCHANT JUMBO KIT SIRINGA 30GR + ACCESSORI",
                    "brand": "KERR",
                    "image": "00077561_.JPG",
                    "discount_percent": 45,
                    "original_price": 73.9,
                    "discount_price": 40.65,
                },
                {
                    "code": "F2201012",
                    "description": "CUTANPLAST DENTAL SPUGNE 24pz",
                    "brand": "OGNA",
                    "image": "00029975_.JPG",
                    "discount_percent": 45,
                    "original_price": 19.9,
                    "discount_price": 10.95,
                },
                {
                    "code": "F2201155",
                    "description": "FM1 MANTELLINE COLORATE IN ROTOLO",
                    "brand": "GLINE",
                    "image": "00079607_.JPG",
                    "discount_percent": 42,
                    "original_price": 11.9,
                    "discount_price": 6.9,
                },
                {
                    "code": "F2201161",
                    "description": "GHIACCIO ISTANTANEO GLINE BUSTE TNT 25PZ",
                    "brand": "GLINE",
                    "image": "00082637_.JPG",
                    "discount_percent": 40,
                    "original_price": 16.5,
                    "discount_price": 9.9,
                },
                {
                    "code": "F2201121",
                    "description": "FM1 SPECCHIETTI PIANI GLINE",
                    "brand": "GLINE",
                    "image": "00129862_.JPG",
                    "discount_percent": 40,
                    "original_price": 21.5,
                    "discount_price": 12.9,
                },
                {
                    "code": "F2201011",
                    "description": "SPONGOSTAN DENTAL 10X10X10MM 24PZ",
                    "brand": "ETHICON",
                    "image": "00006175_.JPG",
                    "discount_percent": 40,
                    "original_price": 32.9,
                    "discount_price": 19.7,
                },
                {
                    "code": "F2201154",
                    "description": "FM1 SALVIETTE FLOW PACK 50X10PZ",
                    "brand": "GLINE",
                    "image": "00105438_.JPG",
                    "discount_percent": 40,
                    "original_price": 21.0,
                    "discount_price": 12.6,
                },
                {
                    "code": "F2201455",
                    "description": "FM1 PENNELLINI G LINE",
                    "brand": "GLINE",
                    "image": "00081938_.JPG",
                    "discount_percent": 40,
                    "original_price": 6.5,
                    "discount_price": 3.9,
                },
                {
                    "code": "F2201010",
                    "description": "ASA SIRINGA 3 ANELLI 0480-1",
                    "brand": "ASA",
                    "image": "00044814_.JPG",
                    "discount_percent": 39,
                    "original_price": 33.0,
                    "discount_price": 20.1,
                },
                {
                    "code": "F2201164",
                    "description": "DS40+ STERILIZZANTE BARATTOLO 1kg",
                    "brand": "GLINE",
                    "image": "00081679_.JPG",
                    "discount_percent": 36,
                    "original_price": 63.5,
                    "discount_price": 40.6,
                },
                {
                    "code": "F2201165",
                    "description": "DD20+ DISINFETTANTE BARATTOLO 2kg",
                    "brand": "GLINE",
                    "image": "00081677_.JPG",
                    "discount_percent": 36,
                    "original_price": 49.5,
                    "discount_price": 31.5,
                },
                {
                    "code": "F2201212",
                    "description": "FITT COMPLETO",
                    "brand": "KERR",
                    "image": "00001524_.JPG",
                    "discount_percent": 36,
                    "original_price": 65.5,
                    "discount_price": 41.9,
                },
                {
                    "code": "F2201181",
                    "description": "BOWIE & DICK BCLEAN 10PZ",
                    "brand": "DEMARCO",
                    "image": "00137108_.JPG",
                    "discount_percent": 35,
                    "original_price": 45.0,
                    "discount_price": 29.25,
                },
                {
                    "code": "F2201005",
                    "description": "FM1 ANESTETICO CITOCARTIN",
                    "brand": "MOLTENI",
                    "image": "00078099_.JPG",
                    "discount_percent": 36,
                    "original_price": 30.9,
                    "discount_price": 19.9,
                },
                {
                    "code": "F2201157",
                    "description": "VASSOI MONOUSO G LINE MAXI ZIGRINATI 28X18CM 400PZ",
                    "brand": "GLINE",
                    "image": "00097324_.JPG",
                    "discount_percent": 35,
                    "original_price": 37.5,
                    "discount_price": 24.4,
                },
                {
                    "code": "F2201003",
                    "description": "FM1 ANESTETICO ARTICAINA PIERREL",
                    "brand": "PIERREL",
                    "image": "00069030_.JPG",
                    "discount_percent": 32,
                    "original_price": 58.5,
                    "discount_price": 39.9,
                },
                {
                    "code": "F2201004",
                    "description": "FM1 ANESTETICO MEPIVACAINA PIERREL",
                    "brand": "PIERREL",
                    "image": "00069026_.JPG",
                    "discount_percent": 32,
                    "original_price": 58.5,
                    "discount_price": 39.9,
                },
                {
                    "code": "F2201170",
                    "description": "FD 322 DISINF. SUPERFICI FLACONE 2,5LT",
                    "brand": "DURR",
                    "image": "00014929_.JPG",
                    "discount_percent": 30,
                    "original_price": 52.0,
                    "discount_price": 36.4,
                },
                {
                    "code": "F2201171",
                    "description": "FD 333 DISINF. SUPERFICI FLACONE 2,5LT",
                    "brand": "DURR",
                    "image": "00034379_.JPG",
                    "discount_percent": 30,
                    "original_price": 55.9,
                    "discount_price": 39.0,
                },
                {
                    "code": "F2201156",
                    "description": "FM1 ASPIRASALIVA COLORATI 100PZ",
                    "brand": "GLINE",
                    "image": "00046854_.JPG",
                    "discount_percent": 30,
                    "original_price": 2.5,
                    "discount_price": 1.75,
                },
                {
                    "code": "F2201140",
                    "description": "EDTA 17% FLACONE 50gr",
                    "brand": "OGNA",
                    "image": "00040476_.JPG",
                    "discount_percent": 31,
                    "original_price": 34.5,
                    "discount_price": 23.9,
                },
                {
                    "code": "F2201179",
                    "description": "VAPOR LINE EXTENDER INTEGRATORI 250pz",
                    "brand": "BS MEDICAL",
                    "image": "00018800_.JPG",
                    "discount_percent": 30,
                    "original_price": 129.5,
                    "discount_price": 90.6,
                },
                {
                    "code": "F2201174",
                    "description": "ID 212 DISINF. STRUMENTI FLACONE 2,5LT",
                    "brand": "DURR",
                    "image": "00003261_.JPG",
                    "discount_percent": 30,
                    "original_price": 67.5,
                    "discount_price": 47.25,
                },
                {
                    "code": "F2201175",
                    "description": "ID 212 FORTE DISINF. STRUMENTI FLACONE 2,5LT",
                    "brand": "DURR",
                    "image": "00029123_.JPG",
                    "discount_percent": 30,
                    "original_price": 69.5,
                    "discount_price": 48.9,
                },
                {
                    "code": "F2201139",
                    "description": "NICLOR 5 DENTALE 5% SODIO IPOCL. 250ML",
                    "brand": "OGNA",
                    "image": "00002426_.JPG",
                    "discount_percent": 30,
                    "original_price": 14.7,
                    "discount_price": 10.3,
                },
                {
                    "code": "F2201002",
                    "description": "FM1 ANESTETICO SCANDONEST",
                    "brand": "SEPTODONT",
                    "image": "00002416_.JPG",
                    "discount_percent": 30,
                    "original_price": 31.7,
                    "discount_price": 22.2,
                },
                {
                    "code": "F2201001",
                    "description": "FM1 ANESTETICO SEPTANEST",
                    "brand": "SEPTODONT",
                    "image": "00015996_.JPG",
                    "discount_percent": 27,
                    "original_price": 31.9,
                    "discount_price": 23.2,
                },
                {
                    "code": "F2201216",
                    "description": "RACESTYPTINE SOLUZIONE 13ML",
                    "brand": "SEPTODONT",
                    "image": "00002449_.JPG",
                    "discount_percent": 28,
                    "original_price": 35.5,
                    "discount_price": 25.6,
                },
                {
                    "code": "F2201191",
                    "description": "FM1 DIGA HYGENIC FOGLI MEDIUM 36PZ",
                    "brand": "HYGENIC",
                    "image": "00009155_.JPG",
                    "discount_percent": 26,
                    "original_price": 18.9,
                    "discount_price": 13.9,
                },
                {
                    "code": "F2201051",
                    "description": "SUNSEPT 290K RAPID NEUTRO DISINF. SUPERFICI 2.5L",
                    "brand": "SUNSEPT",
                    "image": "00099383_.JPG",
                    "discount_percent": 25,
                    "original_price": 43.5,
                    "discount_price": 32.6,
                },
                {
                    "code": "F2201159",
                    "description": "FM1 RULLI SALIVARI G LINE",
                    "brand": "GLINE",
                    "image": "00119071_.JPG",
                    "discount_percent": 50,
                    "original_price": 10.5,
                    "discount_price": 5.25,
                },
                {
                    "code": "F2201229",
                    "description": "ORALSAN COLLUTORIO 0.20% FLACONE 6X1000ML",
                    "brand": "IDS",
                    "image": "00074399_.JPG",
                    "discount_percent": 45,
                    "original_price": 107.9,
                    "discount_price": 59.4,
                },
                {
                    "code": "F2201195",
                    "description": "FM1 PASTA PROFILASSI CLEANIC TUBE",
                    "brand": "KERR",
                    "image": "00062136_.JPG",
                    "discount_percent": 41,
                    "original_price": 25.5,
                    "discount_price": 14.9,
                },
                {
                    "code": "F2201184",
                    "description": "TAPPETO DECONTAMINANTE BLU 45X115CM CF. 4X30 STRATI",
                    "brand": "NEWPLASTIDENT",
                    "image": "00040475_.JPG",
                    "discount_percent": 40,
                    "original_price": 82.5,
                    "discount_price": 49.5,
                },
                {
                    "code": "F2201470",
                    "description": "FM1 CUNEI LEGNO KERR",
                    "brand": "KERR",
                    "image": "00009353_.JPG",
                    "discount_percent": 40,
                    "original_price": 15.7,
                    "discount_price": 9.4,
                },
                {
                    "code": "F2201141",
                    "description": "FM1 CEMENTO PULP CANAL SEALER KIT",
                    "brand": "KERR-ENDO",
                    "image": "00001573_.JPG",
                    "discount_percent": 38,
                    "original_price": 86.0,
                    "discount_price": 52.9,
                },
                {
                    "code": "F2201017",
                    "description": "TOKUYAMA REBASE II FAST KIT",
                    "brand": "TOKUYAMA",
                    "image": "00037702_.JPG",
                    "discount_percent": 34,
                    "original_price": 136.55,
                    "discount_price": 90.5,
                },
                {
                    "code": "F2201006",
                    "description": "FM1 ANESTETICO OPTOCAIN",
                    "brand": "MOLTENI",
                    "image": "00004997_.JPG",
                    "discount_percent": 33,
                    "original_price": 28.9,
                    "discount_price": 19.5,
                },
                {
                    "code": "F2201451",
                    "description": "FM1 MICROAPPLICATORI AKZENTA",
                    "brand": "AKZENTA",
                    "image": "00121062_.JPG",
                    "discount_percent": 30,
                    "original_price": 23.5,
                    "discount_price": 16.45,
                },
                {
                    "code": "F2201198",
                    "description": "SPAZZOLINI PROPHY LINE NYLON C/A 60pz G LINE",
                    "brand": "GLINE",
                    "image": "00081735_.JPG",
                    "discount_percent": 30,
                    "original_price": 46.5,
                    "discount_price": 32.5,
                },
                {
                    "code": "F2201237",
                    "description": "ASPIRASALIVA HYGOFORMIC BIO VERDE LIME 100PZ",
                    "brand": "ORSING",
                    "image": "00139014_.JPG",
                    "discount_percent": 40,
                    "original_price": 10.5,
                    "discount_price": 6.3,
                },
                {
                    "code": "F2201460",
                    "description": "FM1 STRISCE DIAMANTATE EDENTA",
                    "brand": "EDENTA",
                    "image": "00088405_.JPG",
                    "discount_percent": 38,
                    "original_price": 51.9,
                    "discount_price": 32.0,
                },
                {
                    "code": "F2201015",
                    "description": "FM1 VESTIGE RIBASANTI 2X50ML",
                    "brand": "TRAYART",
                    "image": "00104081_.JPG",
                    "discount_percent": 35,
                    "original_price": 42.5,
                    "discount_price": 27.6,
                },
                {
                    "code": "F2201215",
                    "description": "DETARTRINE Z PASTA 45GR",
                    "brand": "SEPTODONT",
                    "image": "00001993_.JPG",
                    "discount_percent": 30,
                    "original_price": 24.9,
                    "discount_price": 17.4,
                },
                {
                    "code": "F2201131",
                    "description": "ULTRA-ETCH SIRINGA INDISPENSE 30ML UP685",
                    "brand": "ULTRADENT",
                    "image": "00051181_.JPG",
                    "discount_percent": 28,
                    "original_price": 84.5,
                    "discount_price": 60.5,
                },
                {
                    "code": "F2201125",
                    "description": "FM1 OT CAP RHEIN",
                    "brand": "RHEIN83",
                    "image": "00006217_.JPG",
                    "discount_percent": 20,
                    "original_price": 26.0,
                    "discount_price": 20.8,
                },
                {
                    "code": "F2201127",
                    "description": "OPTIBOND UNIVERSAL ADHESIVE FL. 5ML 36519",
                    "brand": "KERR",
                    "image": "00122730_.JPG",
                    "discount_percent": 45,
                    "original_price": 89.9,
                    "discount_price": 49.45,
                },
                {
                    "code": "F2201452",
                    "description": "OPALESCENCE BOOST 40% INTRO KIT UP4750",
                    "brand": "ULTRADENT",
                    "image": "00085249_.JPG",
                    "discount_percent": 37,
                    "original_price": 199.9,
                    "discount_price": 126.0,
                },
                {
                    "code": "F2201176",
                    "description": "ZETA 5 POWER ACT DISINF. LIQUIDO CONC. 1 LT",
                    "brand": "ZHERMACK",
                    "image": "00119804_.JPG",
                    "discount_percent": 30,
                    "original_price": 36.9,
                    "discount_price": 25.8,
                },
                {
                    "code": "F2201177",
                    "description": "PULI-JET PLUS 2.0 CONC. CATTANI MAGNOLIA FL. 1LT",
                    "brand": "CATTANI",
                    "image": "00138851_.JPG",
                    "discount_percent": 30,
                    "original_price": 51.5,
                    "discount_price": 36.0,
                },
                {
                    "code": "F2201206",
                    "description": "FM1 FLEXITIME DYNAMIX",
                    "brand": "KULZER",
                    "image": "00065475_.JPG",
                    "discount_percent": 25,
                    "original_price": 195.5,
                    "discount_price": 146.6,
                },
                {
                    "code": "F2201038",
                    "description": "FM1 CEMENTO PANAVIA V5 INTRO KIT",
                    "brand": "KURARAY",
                    "image": "00102933_.JPG",
                    "discount_percent": 37,
                    "original_price": 158.0,
                    "discount_price": 99.5,
                },
                {
                    "code": "F2201039",
                    "description": "FM1 CEMENTO PANAVIA SA CEMENT 8,2GR",
                    "brand": "KURARAY",
                    "image": "00131577_.JPG",
                    "discount_percent": 30,
                    "original_price": 110.0,
                    "discount_price": 77.0,
                },
                {
                    "code": "F2201185",
                    "description": "CANNULE CHIRURGICHE OMNIASURGE 2,5MM 20PZ+ADATTATORE",
                    "brand": "OMNIA",
                    "image": "00047025_.JPG",
                    "discount_percent": 25,
                    "original_price": 27.5,
                    "discount_price": 20.6,
                },
                {
                    "code": "F2201230",
                    "description": "FM1 SCOVOLINI ORALPROX",
                    "brand": "IDS",
                    "image": "00082566_.JPG",
                    "discount_percent": 44,
                    "original_price": 37.5,
                    "discount_price": 20.9,
                },
                {
                    "code": "F2201014",
                    "description": "FM1 VESTIGE PUTTY SOFT 300+300ML",
                    "brand": "TRAYART",
                    "image": "00104080_.JPG",
                    "discount_percent": 43,
                    "original_price": 52.5,
                    "discount_price": 29.9,
                },
                {
                    "code": "F2201146",
                    "description": "FM1 PERNI IN FIBRA CONICAL 10PZ",
                    "brand": "GLINE",
                    "image": "00097577_.JPG",
                    "discount_percent": 33,
                    "original_price": 47.0,
                    "discount_price": 31.5,
                },
                {
                    "code": "F2201160",
                    "description": "COLD SPRAY IPOTERMIZZANTE 200ML",
                    "brand": "GLINE",
                    "image": "00138440_.JPG",
                    "discount_percent": 50,
                    "original_price": 11.5,
                    "discount_price": 5.75,
                },
                {
                    "code": "F2201009",
                    "description": "LIDOCAINA 15% SPRAY FLACONE 50GR (F)",
                    "brand": "OGNA",
                    "image": "00002422_.JPG",
                    "discount_percent": 40,
                    "original_price": 24.9,
                    "discount_price": 14.9,
                },
                {
                    "code": "F2201008",
                    "description": "FM1 AGHI SEPTOJECT 100PZ",
                    "brand": "SEPTODONT",
                    "image": "00091404_.JPG",
                    "discount_percent": 36,
                    "original_price": 15.5,
                    "discount_price": 9.9,
                },
                {
                    "code": "F2201180",
                    "description": "HELIX TEST BCLEAN 250PZ + 1 CANNULA",
                    "brand": "DEMARCO",
                    "image": "00137107_.JPG",
                    "discount_percent": 36,
                    "original_price": 105.5,
                    "discount_price": 67.5,
                },
                {
                    "code": "F2201016",
                    "description": "VESTIGE BITE 2X50ML +6 PUNTALI VERDI",
                    "brand": "TRAYART",
                    "image": "00104083_.JPG",
                    "discount_percent": 35,
                    "original_price": 42.9,
                    "discount_price": 27.9,
                },
                {
                    "code": "F2201208",
                    "description": "FM1 FLEXITIME FLOW",
                    "brand": "KULZER",
                    "image": "00031813_.JPG",
                    "discount_percent": 28,
                    "original_price": 66.5,
                    "discount_price": 47.9,
                },
                {
                    "code": "F2201042",
                    "description": "SUPER ETCH JUMBO SIRINGA 2X25ML",
                    "brand": "SDI",
                    "image": "00045531_.JPG",
                    "discount_percent": 40,
                    "original_price": 73.9,
                    "discount_price": 44.3,
                },
                {
                    "code": "F2201013",
                    "description": "DIA DENTAL ALGINATO BUSTA 453GR",
                    "brand": "TRAYART",
                    "image": "00107390_.JPG",
                    "discount_percent": 45,
                    "original_price": 12.5,
                    "discount_price": 6.9,
                },
                {
                    "code": "F2201018",
                    "description": "FM1 TOKUYAMA SOFRELINE TOUGH",
                    "brand": "TOKUYAMA",
                    "image": "00040311_.JPG",
                    "discount_percent": 29,
                    "original_price": 122.75,
                    "discount_price": 87.0,
                },
                {
                    "code": "F2201454",
                    "description": "FM1 OPALCESCE PF PAZIENTE",
                    "brand": "ULTRADENT",
                    "image": "00092655_.JPG",
                    "discount_percent": 25,
                    "original_price": 74.9,
                    "discount_price": 55.9,
                },
                {
                    "code": "F2201182",
                    "description": "PELLICOLE PROTETTIVE PERFECTO BLU TRASPARENTE 1200 STRAPPI (CM10X15)",
                    "brand": "PERFECTO",
                    "image": "00131636_.JPG",
                    "discount_percent": 50,
                    "original_price": 21.8,
                    "discount_price": 10.9,
                },
                {
                    "code": "F2201128",
                    "description": "OPTIBOND EXTRA UNIVERSAL KIT 36658",
                    "brand": "KERR",
                    "image": "00130656_.JPG",
                    "discount_percent": 45,
                    "original_price": 201.0,
                    "discount_price": 110.5,
                },
                {
                    "code": "F2201197",
                    "description": "FM1 SPAZZOLINI PRO-CUP",
                    "brand": "KERR",
                    "image": "00027720_.JPG",
                    "discount_percent": 41,
                    "original_price": 33.5,
                    "discount_price": 19.1,
                },
                {
                    "code": "F2201183",
                    "description": "FM1 FILM PROTETTITIVI IN ROTOLO PERFECTO",
                    "brand": "PERFECTO",
                    "image": "00131638_.JPG",
                    "discount_percent": 35,
                    "original_price": 32.5,
                    "discount_price": 21.1,
                },
                {
                    "code": "F2201162",
                    "description": "FM1 DEFLUSSORI STERILI 10PZ",
                    "brand": "GLINE",
                    "image": "00094645_.JPG",
                    "discount_percent": 35,
                    "original_price": 55.9,
                    "discount_price": 36.3,
                },
                {
                    "code": "F2201062",
                    "description": "FM1 COMPOSITO HERCULITE XRV ULTRA FLOW",
                    "brand": "KERR",
                    "image": "00108354_.JPG",
                    "discount_percent": 35,
                    "original_price": 48.5,
                    "discount_price": 31.5,
                },
                {
                    "code": "F2201037",
                    "description": "FM1 FRESE TAGLIACORONA JET BEAVER",
                    "brand": "JET BEAVERS",
                    "image": "00005027_.JPG",
                    "discount_percent": 40,
                    "original_price": 25.3,
                    "discount_price": 15.2,
                },
                {
                    "code": "F2201236",
                    "description": "ASCIUGAMANI BIO BIB PIEGATI A C RICICLATO GRIGIO NAT. 1V. 3000PZ",
                    "brand": "LARIDENT",
                    "image": "00129995_.JPG",
                    "discount_percent": 30,
                    "original_price": 29.5,
                    "discount_price": 20.65,
                },
                {
                    "code": "F2201235",
                    "description": "BICCHIERI BIO CUP PLA TRASPARENTI 166CC 50PZ",
                    "brand": "LARIDENT",
                    "image": "00129993_.JPG",
                    "discount_percent": 40,
                    "original_price": 4.5,
                    "discount_price": 2.7,
                },
                {
                    "code": "F2201060",
                    "description": "FM1 COMPOSITO SIMPLISHADE UNIVERSAL 4GR",
                    "brand": "KERR",
                    "image": "00138606_.JPG",
                    "discount_percent": 48,
                    "original_price": 62.9,
                    "discount_price": 32.7,
                },
                {
                    "code": "F2201007",
                    "description": "FM1 AGHI PER ANESTESIA PJECT 100PZ",
                    "brand": "SIMIT",
                    "image": "00123561_.JPG",
                    "discount_percent": 48,
                    "original_price": 12.9,
                    "discount_price": 6.7,
                },
                {
                    "code": "F2201126",
                    "description": "FM1 OT EQUATOR CAPPETTE",
                    "brand": "RHEIN83",
                    "image": "00079669_.JPG",
                    "discount_percent": 20,
                    "original_price": 28.0,
                    "discount_price": 22.4,
                },
                {
                    "code": "F2201232",
                    "description": "SALVIETTE MONOART NATURA TOWEL UP 500PZ (10X50PZ)",
                    "brand": "EURONDA",
                    "image": "00138418_.JPG",
                    "discount_percent": 35,
                    "original_price": 26.9,
                    "discount_price": 17.5,
                },
                {
                    "code": "F2201047",
                    "description": "POLA OFFICE+ KIT 3 PAZIENTI C/OPTRAGATE",
                    "brand": "SDI",
                    "image": "00092625_.JPG",
                    "discount_percent": 31,
                    "original_price": 229.0,
                    "discount_price": 159.0,
                },
                {
                    "code": "F2201190",
                    "description": "FM1 OPTIDISC KERR",
                    "brand": "KERR",
                    "image": "00078388_.JPG",
                    "discount_percent": 51,
                    "original_price": 38.5,
                    "discount_price": 18.95,
                },
                {
                    "code": "F2201040",
                    "description": "KATANA CLEANER FLACONE 4ML 3970-EU",
                    "brand": "KURARAY",
                    "image": "00135554_.JPG",
                    "discount_percent": 30,
                    "original_price": 29.0,
                    "discount_price": 20.3,
                },
                {
                    "code": "F2201172",
                    "description": "FD 350 CLASSIC FAZZOLETTI 8 RICAMBI + 2 BARATTOLI",
                    "brand": "DURR",
                    "image": "00011931_.JPG",
                    "discount_percent": 30,
                    "original_price": 89.9,
                    "discount_price": 62.9,
                },
                {
                    "code": "F2201231",
                    "description": "MANTELLINE MONOART NATURA PG30 ROTOLO 80 STRAPPI",
                    "brand": "EURONDA",
                    "image": "00138417_.JPG",
                    "discount_percent": 34,
                    "original_price": 14.2,
                    "discount_price": 9.4,
                },
                {
                    "code": "F2201068",
                    "description": "FM1 MY IMPLANT INTESA MONC.TIT. ANG.",
                    "brand": "MYIMPLANT",
                    "image": "00088753_.JPG",
                    "discount_percent": 25,
                    "original_price": 65.0,
                    "discount_price": 48.5,
                },
                {
                    "code": "F2201147",
                    "description": "FM1 PERNI IN FIBRA CILINDRICI 10PZ",
                    "brand": "GLINE",
                    "image": "00097569_.JPG",
                    "discount_percent": 33,
                    "original_price": 47.0,
                    "discount_price": 31.5,
                },
                {
                    "code": "F2201173",
                    "description": "ZERO #901 DETERGENTE ALGINATO 906GR",
                    "brand": "TRAYART",
                    "image": "00112448_.JPG",
                    "discount_percent": 52,
                    "original_price": 34.5,
                    "discount_price": 16.5,
                },
                {
                    "code": "F2201138",
                    "description": "FM1 AGHI IRRIGATION PROBE 40PZ",
                    "brand": "KERR",
                    "image": "00043926_.JPG",
                    "discount_percent": 30,
                    "original_price": 47.9,
                    "discount_price": 33.5,
                },
                {
                    "code": "F2201188",
                    "description": "FM1 PUNTALI RISKONTROL PERFECT SYSTEM 250PZ",
                    "brand": "RISKONTROL",
                    "image": "00092379_.JPG",
                    "discount_percent": 30,
                    "original_price": 43.9,
                    "discount_price": 30.7,
                },
                {
                    "code": "F2201021",
                    "description": "BIO-GEN PUTTY SPONGIOSA FLACONE 0,50GR BGP-01S",
                    "brand": "BIOTECK",
                    "image": "00073689_.JPG",
                    "discount_percent": 30,
                    "original_price": 91.0,
                    "discount_price": 64.0,
                },
                {
                    "code": "F2201133",
                    "description": "PORCELAIN ETCH KIT UP405",
                    "brand": "ULTRADENT",
                    "image": "00049701_.JPG",
                    "discount_percent": 52,
                    "original_price": 96.5,
                    "discount_price": 46.45,
                },
                {
                    "code": "F2201238",
                    "description": "ADATTATORE HYGOFORMIC BIO 100PZ",
                    "brand": "ORSING",
                    "image": "00139015_.JPG",
                    "discount_percent": 30,
                    "original_price": 8.5,
                    "discount_price": 5.95,
                },
                {
                    "code": "F2201178",
                    "description": "ID 215 DISINF. STRUMENTI ENZIMATICO FLACONE 2,5LT",
                    "brand": "DURR",
                    "image": "00117339_.JPG",
                    "discount_percent": 28,
                    "original_price": 68.0,
                    "discount_price": 48.65,
                },
                {
                    "code": "F2201200",
                    "description": "FM1 APPLICATORI DOPPI PER FLUORO 50PZ",
                    "brand": "VARI",
                    "image": "00141401_.JPG",
                    "discount_percent": 28,
                    "original_price": 38.5,
                    "discount_price": 27.6,
                },
                {
                    "code": "F2201209",
                    "description": "FM1 PORTAIMPRONTE PVC",
                    "brand": "LARIDENT",
                    "image": "00116719_.JPG",
                    "discount_percent": 33,
                    "original_price": 9.9,
                    "discount_price": 6.65,
                },
                {
                    "code": "F2201027",
                    "description": "FM1 COMPOSITO BEAUTIFIL FLOW PLUS X F00",
                    "brand": "SHOFU",
                    "image": "00141205_.JPG",
                    "discount_percent": 28,
                    "original_price": 36.5,
                    "discount_price": 26.25,
                },
                {
                    "code": "F2201233",
                    "description": "VASSOI MONOUSO BIO PLA TRASP. 28X18CM 100PZ",
                    "brand": "LARIDENT",
                    "image": "00129992_.JPG",
                    "discount_percent": 25,
                    "original_price": 32.5,
                    "discount_price": 24.3,
                },
            ]
        }
        self.write(response)
